use libc::c_char;

/*
** Information about each column of an SQL table is held in an instance
** of the Column structure, in the Table.aCol[] array.
**
** Definitions:
**
**   "table column index"     This is the index of the column in the
**                            Table.aCol[] array, and also the index of
**                            the column in the original CREATE TABLE stmt.
**
**   "storage column index"   This is the index of the column in the
**                            record BLOB generated by the OP_MakeRecord
**                            opcode.  The storage column index is less than
**                            or equal to the table column index.  It is
**                            equal if and only if there are no VIRTUAL
**                            columns to the left.
**
** Notes on zCnName:
** The zCnName field stores the name of the column, the datatype of the
** column, and the collating sequence for the column, in that order, all in
** a single allocation.  Each string is 0x00 terminated.  The datatype
** is only included if the COLFLAG_HASTYPE bit of colFlags is set and the
** collating sequence name is only included if the COLFLAG_HASCOLL bit is
** set.
*/
#[repr(C)]
pub struct Column {
    zCnName: *mut c_char, /* Name of this column */

    // TODO: merge notNull and eCType into a single 8-bit field
    notNull: u8, /* An OE_ code for handling a NOT NULL constraint */
    eCType: u8,  /* One of the standard types */

    affinity: c_char, /* One of the SQLITE_AFF_... values */
    szEst: u8,        /* Est size of value in this column. sizeof(INT)==1 */
    hName: u8,        /* Column name hash for faster lookup */
    iDflt: u16,       /* 1-based index of DEFAULT.  0 means "none" */
    colFlags: u16,    /* Boolean properties.  See COLFLAG_ defines below */
}

/* Allowed values for Column.eCType.
**
** Values must match entries in the global constant arrays
** sqlite3StdTypeLen[] and sqlite3StdType[].  Each value is one more
** than the offset into these arrays for the corresponding name.
** Adjust the SQLITE_N_STDTYPE value if adding or removing entries.
*/
#[repr(C)]
pub enum Coltype {
    Custom = 0,
    Any = 1,
    Blob = 2,
    Int = 3,
    Integer = 4,
    Real = 5,
    Text = 6,
}

pub const SQLITE_N_STDTYPE: u8 = 6; /* Number of standard types */

/* Allowed values for Column.colFlags.
**
** Constraints:
**         TF_HasVirtual == COLFLAG_VIRTUAL
**         TF_HasStored  == COLFLAG_STORED
**         TF_HasHidden  == COLFLAG_HIDDEN
*/
#[repr(C)]
pub enum Colflag {
    Primkey = 0x0001,   /* Column is part of the primary key */
    Hidden = 0x0002,    /* A hidden column in a virtual table */
    Hastype = 0x0004,   /* Type name follows column name */
    Unique = 0x0008,    /* Column def contains "UNIQUE" or "PK" */
    Sorterref = 0x0010, /* Use sorter-refs with this column */
    Virtual = 0x0020,   /* GENERATED ALWAYS AS ... VIRTUAL */
    Stored = 0x0040,    /* GENERATED ALWAYS AS ... STORED */
    Notavail = 0x0080,  /* STORED column not yet calculated */
    Busy = 0x0100,      /* Blocks recursion on GENERATED columns */
    Hascoll = 0x0200,   /* Has collating sequence name in zCnName */
    Noexpand = 0x0400,  /* Omit this column when expanding "*" */
    Generated = 0x0060, /* Combo: _STORED, _VIRTUAL */
    Noinsert = 0x0062,  /* Combo: _HIDDEN, _STORED, _VIRTUAL */
}
